version: '3.8'

services:
  clea-webui:
    build:
      context: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PUBLIC_API_URL=http://clea-api:8080
    networks:
      - clea-network

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - clea-webui
    networks:
      - clea-network
    restart: unless-stopped

networks:
  clea-network:
    driver: bridge
